import {test,expect} from '@playwright/test';

test('desktop conversation, checks, replan, persistence and isolation',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 const request=page.request;
 await request.post('/api/auth/setup',{data:{username:'desktop-tester',password:'desktop-test-password-2026'}});
 const t=(await (await request.post('/api/tenants',{data:{name:'Desktop test workspace'}})).json()).id;
 await request.post(`/api/t/${t}/models`,{data:{name:'Verification model',provider:'custom_openai',model_name:'test-model',base_url:'http://127.0.0.1:9999/v1'}});
 await page.goto('/');
 await page.getByRole('button',{name:'Create your first project',exact:true}).click();
 await page.getByLabel('Project name',{exact:true}).fill('Authentication project');
 await page.getByRole('button',{name:'Create project',exact:true}).click();
 await expect(page.getByRole('heading',{name:'What are we working on?'})).toBeVisible();
 await page.getByLabel('Ask Frontier',{exact:true}).fill('Build the authentication API.');
 await page.getByLabel('Ask Frontier',{exact:true}).press('Enter');
 await expect(page.getByText('Working with your AI team',{exact:true})).toBeVisible();
 await expect(page.getByText(/Complete · Approved by reviewer/)).toBeVisible({timeout:45000});
 await expect(page.getByText('Iteration 2 of 3',{exact:true})).toBeVisible();
 await expect(page.getByText('Missing ownership check',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Open changes',exact:true}).click();
 await expect(page.getByLabel('Changed file')).toBeVisible();
 await page.getByLabel('Changed file').selectOption({label:'result.py · iteration 1 · applied'});
 await expect(page.locator('.unified-diff')).toContainText('return 42');
 await page.getByRole('button',{name:'Toggle split diff'}).click();
 await expect(page.locator('.split-diff')).toBeVisible();
 await page.screenshot({path:'test-results/desktop-changes.png'});
 await page.getByRole('button',{name:'Open terminal',exact:true}).click();
 await expect(page.locator('.terminal-output')).toContainText('OK');
 await expect(page.locator('.terminal-output')).toContainText('Process exited with code 0');
 await page.getByRole('button',{name:'Open project files',exact:true}).click();
 await page.getByRole('button',{name:/^result.py/}).click();
 await expect(page.locator('.file-preview')).toContainText('return 42');
 await page.getByRole('button',{name:'Plan',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Implementation plan',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Review',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Approved by your reviewer'})).toBeVisible();
 await page.getByRole('button',{name:'Close contextual panel'}).click();
 await page.reload();
 await expect(page.getByText(/Complete · Approved by reviewer/)).toBeVisible();
 await page.getByLabel('Ask Frontier',{exact:true}).fill('Review the project again and preserve the working tests.');
 await page.getByLabel('Ask Frontier',{exact:true}).press('Enter');
 await expect(page.getByText(/Complete · Approved by reviewer/)).toHaveCount(2,{timeout:45000});
 await page.getByRole('button',{name:'Settings',exact:true}).click();
 for(const tab of ['Models & Providers','AI Team','Prompts','Workspaces','Execution','Usage & Limits','Security','Developer','General']){
  await page.getByRole('button',{name:tab,exact:true}).click();
  await expect(page.locator('.desktop-settings-body')).not.toContainText('Loading settings');
 }
 await page.getByRole('button',{name:'Execution',exact:true}).click();
 await page.getByRole('button',{name:'Run history',exact:true}).click();
 await expect(page.locator('.desktop-settings-body table')).toContainText('Build the authentication API.');
 await page.getByRole('link',{name:'Open run Build the authentication API.',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Workflow complete. Reviewed and approved.'})).toBeVisible();
 await page.getByRole('button',{name:'General',exact:true}).click();
 await page.getByRole('button',{name:'Light Clear and open',exact:true}).click();
 await expect(page.locator('html')).toHaveAttribute('data-theme','light');
 await page.getByRole('button',{name:'Dark Focused and understated',exact:true}).click();
 await page.getByRole('button',{name:'Close dialog',exact:true}).click();
 const b=(await (await request.post('/api/tenants',{data:{name:'Isolated second workspace'}})).json()).id;
 const p=(await (await request.get(`/api/t/${t}/projects`)).json())[0];
 await page.reload();
 await page.getByLabel('Current workspace',{exact:true}).selectOption(b);
 await expect(page.getByRole('heading',{name:'Open a project. Start a conversation.'})).toBeVisible();
 await expect(page.getByText('Authentication project',{exact:true})).toHaveCount(0);
 expect((await request.get(`/api/t/${b}/projects/${p.id}/files`)).status()).toBe(403);
 await page.getByLabel('Current workspace',{exact:true}).selectOption(t);
 await expect(page.getByText(/Complete · Approved by reviewer/)).toHaveCount(2);
 await page.screenshot({path:'test-results/desktop-session.png'});
 expect(errors).toEqual([]);
});
