import {useEffect,useState} from 'react';
import {Moon,Sun,ShieldCheck,RefreshCw,Bell,Palette} from 'lucide-react';
import {getVersion} from '@tauri-apps/api/app';
import {useWorkspace,THEMES} from '../../app/context';
import {Field} from '../../components/ui';
import {isTauri,notifyLevel,setNotifyLevel,chime,type NotifyLevel} from '../../lib/notify';
import type {useUpdate} from '../../app/Updater';
export default function Settings({section='General',updater}:{section?:string;updater?:ReturnType<typeof useUpdate>}){
 const {theme,setTheme,accent,setAccent,tenant,tenants,switchTenant,advanced,setAdvanced}=useWorkspace();
 const [notify,setNotify]=useState<NotifyLevel>(notifyLevel());const [version,setVersion]=useState('');
 useEffect(()=>{if(isTauri())getVersion().then(setVersion).catch(()=>{})},[]);
 if(section==='Security')return <section className="form-panel"><h3><ShieldCheck size={18}/> Security</h3><p>Projects, agents, conversations, and their file changes are scoped to the selected workspace. The backend validates ownership on every request.</p><p>API keys are encrypted in local application storage and never included in the frontend. Subscription logins are held by their own command line tool, outside this application.</p><h3>Local execution</h3><p>An agent works inside the project folder with your operating-system account permissions. Read only lets it look without changing anything, Edit files lets it write, and Full auto also lets it run commands. These are the agent tool's own permission settings, not an operating-system sandbox, and they are chosen per turn.</p><p>Frontier's own file views exclude credentials, linked directories, and paths outside the selected root. A subscription login's credentials are held by its command line tool in a directory per account and are never read by Frontier.</p></section>;
 if(section==='Developer')return <section className="form-panel"><h3>Developer</h3><label className="toggle-row"><div><strong>Advanced output</strong><p>Show extra detail in output views.</p></div><input type="checkbox" role="switch" checked={advanced} onChange={e=>setAdvanced(e.target.checked)}/></label><dl className="metadata"><dt>Runtime</dt><dd>Tauri desktop + Python harness driving local agent CLIs</dd><dt>Live updates</dt><dd>Persisted server events with polling recovery</dd><dt>Persistence</dt><dd>Local SQLite database</dd><dt>Recovery</dt><dd>A turn interrupted by a restart is closed out, never replayed.</dd></dl></section>;
 return <section className="form-panel"><h3>Appearance</h3><div className="theme-options">{THEMES.map(t=><button key={t.id} className={theme===t.id?'selected':''} onClick={()=>setTheme(t.id)}>{t.dark?<Moon size={22}/>:<Sun size={22}/>}<strong>{t.name}</strong><span>{t.blurb}</span></button>)}</div><Field label="Accent colour" hint="Buttons, links and highlights. Clear it to use the theme's own."><div className="accent-row"><Palette size={14}/><input type="color" aria-label="Accent colour" value={/^#[0-9a-fA-F]{6}$/.test(accent)?accent:'#6b63e8'} onChange={e=>setAccent(e.target.value)}/>{['#6b63e8','#2f7cf6','#0ea5a4','#d97706','#dc4c6c','#7c3aed'].map(c=><button key={c} type="button" className={`swatch ${accent===c?'selected':''}`} style={{background:c}} aria-label={`Use ${c}`} onClick={()=>setAccent(c)}/>)}{accent&&<button type="button" onClick={()=>setAccent('')}>Theme default</button>}</div></Field><Field label="Default / current workspace" hint="Your selection is remembered on this device."><select value={tenant?.id||''} onChange={e=>switchTenant(e.target.value)}>{tenants.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></Field><h3><Bell size={16}/> Notifications</h3><Field label="When a turn finishes while Frontier is in the background" hint="Nothing is shown while the window has focus."><select value={notify} onChange={e=>{const v=e.target.value as NotifyLevel;setNotify(v);setNotifyLevel(v);if(v==='sound')chime()}}><option value="sound">Desktop notification with a chime</option><option value="silent">Desktop notification, no sound</option><option value="off">Off</option></select></Field><h3><RefreshCw size={16}/> Updates</h3><p className="muted">Frontier checks GitHub releases once at launch{version&&` · version ${version}`}.</p>{updater&&isTauri()&&<div className="actions"><button onClick={()=>updater.lookFor()} disabled={updater.state==='checking'||updater.state==='installing'}>{updater.state==='checking'?'Checking…':'Check for updates'}</button><span className="muted">{updater.update?`Frontier ${updater.update.version} is available.`:updater.state==='current'?'You are on the latest version.':updater.state==='error'?updater.error:''}</span>{updater.update&&<button className="primary" disabled={updater.state==='installing'} onClick={()=>updater.install()}>{updater.state==='installing'?'Installing…':'Install and restart'}</button>}</div>}<h3>Keyboard shortcuts</h3><dl className="metadata"><dt>Enter</dt><dd>Send a message, or queue it while a turn is running</dd><dt>Ctrl + Enter</dt><dd>Stop the running turn and send this instead</dd><dt>Shift + Enter</dt><dd>New line</dd><dt>Ctrl + N</dt><dd>New session</dd><dt>Ctrl + K</dt><dd>Find a session</dd><dt>↑ / ↓ in the composer</dt><dd>Walk back through your earlier messages</dd><dt>Ctrl + Shift + S</dt><dd>Stash the draft for later</dd><dt>Right-click a session</dt><dd>Rename, pin, or archive it</dd><dt>Escape</dt><dd>Close the contextual panel</dd></dl></section>;
}
