import {Moon,Sun,ShieldCheck} from 'lucide-react';
import {useWorkspace} from '../../app/context';
import {Field} from '../../components/ui';
export default function Settings({section='General'}:{section?:string}){
 const {theme,setTheme,tenant,tenants,switchTenant,advanced,setAdvanced}=useWorkspace();
 if(section==='Security')return <section className="form-panel"><h3><ShieldCheck size={18}/> Security</h3><p>Projects, agents, conversations, and their file changes are scoped to the selected workspace. The backend validates ownership on every request.</p><p>API keys are encrypted in local application storage and never included in the frontend. Subscription logins are held by their own command line tool, outside this application.</p><h3>Local execution</h3><p>An agent works inside the project folder with your operating-system account permissions. Read only lets it look without changing anything, Edit files lets it write, and Full auto also lets it run commands. These are the agent tool's own permission settings, not an operating-system sandbox, and they are chosen per turn.</p><p>Frontier's own file views exclude credentials, linked directories, and paths outside the selected root. A subscription login's credentials are held by its command line tool in a directory per account and are never read by Frontier.</p></section>;
 if(section==='Developer')return <section className="form-panel"><h3>Developer</h3><label className="toggle-row"><div><strong>Advanced output</strong><p>Show extra detail in output views.</p></div><input type="checkbox" role="switch" checked={advanced} onChange={e=>setAdvanced(e.target.checked)}/></label><dl className="metadata"><dt>Runtime</dt><dd>Tauri desktop + Python harness driving local agent CLIs</dd><dt>Live updates</dt><dd>Persisted server events with polling recovery</dd><dt>Persistence</dt><dd>Local SQLite database</dd><dt>Recovery</dt><dd>A turn interrupted by a restart is closed out, never replayed.</dd></dl></section>;
 return <section className="form-panel"><h3>Appearance</h3><div className="theme-options"><button className={theme==='dark'?'selected':''} onClick={()=>setTheme('dark')}><Moon size={22}/><strong>Dark</strong><span>Focused and understated</span></button><button className={theme==='light'?'selected':''} onClick={()=>setTheme('light')}><Sun size={22}/><strong>Light</strong><span>Clear and open</span></button></div><Field label="Default / current workspace" hint="Your selection is remembered on this device."><select value={tenant?.id||''} onChange={e=>switchTenant(e.target.value)}>{tenants.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></Field><h3>Keyboard shortcuts</h3><dl className="metadata"><dt>Enter</dt><dd>Send a message</dd><dt>Shift + Enter</dt><dd>New line</dd><dt>Ctrl + N</dt><dd>New session</dd><dt>Ctrl + K</dt><dd>Find a session</dd><dt>Escape</dt><dd>Close the contextual panel</dd></dl></section>;
}
