import {useState} from 'react';
import Markdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import rehypeHighlight from 'rehype-highlight';
import {CheckCircle2,AlertTriangle,Download,Copy,FileText,ShieldCheck} from 'lucide-react';
import {useWorkspace} from '../app/context';
import {download} from '../lib/api';
import type {PlanArtifact,ReviewReport,BuildArtifact,StageResult} from '../types';
export function MarkdownOutput({text}:{text:string}){return <div className="markdown"><Markdown remarkPlugins={[remarkGfm]} rehypePlugins={[rehypeHighlight]}>{text}</Markdown></div>}
export function PlanViewer({plan}:{plan:PlanArtifact}){return <div className="plan-view"><span className="artifact-label"><FileText size={15}/>VALIDATED PLAN ARTIFACT</span><h2>{plan.title}</h2><h4>Execution plan</h4><ol className="plan-steps">{plan.execution_steps.map((step,i)=><li key={i}><span>{String(i+1).padStart(2,'0')}</span><MarkdownOutput text={step}/></li>)}</ol><h4>Technical dependencies</h4>{plan.technical_dependencies.length?<div className="dependency-list">{plan.technical_dependencies.map((d,i)=><div key={i}>{Object.entries(d).map(([k,v])=><span key={k}><small>{k}</small>{v}</span>)}</div>)}</div>:<p className="muted">No technical dependencies specified.</p>}<h4>Risk assessment</h4><div className="risk-box"><AlertTriangle size={17}/><MarkdownOutput text={plan.risk_assessment}/></div></div>}
export function ReviewViewer({review}:{review:ReviewReport}){return <div className="review-view"><div className={`review-verdict ${review.approved?'approved':'rejected'}`}><div>{review.approved?<ShieldCheck size={29}/>:<AlertTriangle size={29}/>}<div><span className="eyebrow">REVIEW RESULT</span><h2>{review.approved?'Approved by your reviewer':'Changes required'}</h2></div></div><div className="quality"><strong>{Math.round(review.quality_score*100)}</strong><span>/ 100</span></div></div><div className="quality-bar"><span style={{width:`${review.quality_score*100}%`}}/></div><div className="review-findings"><h4>Security findings <span>{review.detected_vulnerabilities.length}</span></h4>{review.detected_vulnerabilities.length?<ul>{review.detected_vulnerabilities.map((v,i)=><li key={i}><AlertTriangle size={16}/><MarkdownOutput text={v}/></li>)}</ul>:<p><CheckCircle2 size={16}/>No unresolved vulnerabilities reported.</p>}<h4>Reviewer feedback</h4>{review.rejection_reasons.length?<ul>{review.rejection_reasons.map((v,i)=><li key={i}><span className="finding-number">{i+1}</span><MarkdownOutput text={v}/></li>)}</ul>:<p className="muted">The reviewer approved this plan and deliverable against the configured rules.</p>}</div></div>}
export function FilesViewer({stages}:{stages:StageResult[]}){
 const {notify}=useWorkspace();const [open,setOpen]=useState<string|null>(null);
 const files=stages.flatMap(s=>{if(!s.artifact)return [];if(s.role==='building')return (s.artifact as BuildArtifact).files.map((f,i)=>({...f,id:`${s.id}-${i}`}));if(s.role==='planning'||s.role==='review')return [{name:`${s.role==='planning'?'plan':'review'}-iteration-${s.iteration}.json`,content:JSON.stringify(s.artifact,null,2),id:s.id}];return []});
 if(!files.length)return <p className="empty-output">Files and structured artifacts appear here as your team completes each stage.</p>;
 return <div className="files-list">{files.map(f=><section key={f.id}><div className="file-row"><FileText size={18}/><button onClick={()=>setOpen(open===f.id?null:f.id)}>{f.name}<small>{new Blob([f.content]).size.toLocaleString()} bytes</small></button><button className="icon-button" title="Copy file" aria-label={`Copy ${f.name}`} onClick={async()=>{try{await navigator.clipboard.writeText(f.content);notify('Copied to clipboard')}catch{notify('Clipboard unavailable. Download the file instead.')}}}><Copy size={15}/></button><button className="icon-button" title="Download file" aria-label={`Download ${f.name}`} onClick={()=>download(f.name,f.content)}><Download size={16}/></button></div>{open===f.id&&<pre className="code-block">{f.content}</pre>}</section>)}</div>
}
