import {useId,cloneElement,isValidElement,type ReactElement,type ReactNode} from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import {X,ArrowRight,AlertCircle,Workflow,LoaderCircle,Check,RotateCcw} from 'lucide-react';
import {Link} from 'react-router-dom';
import {ApiError} from '../lib/api';
export function Modal({open,onClose,title,description,children,wide=false}:{open:boolean;onClose:()=>void;title:string;description?:string;children:ReactNode;wide?:boolean}){return <Dialog.Root open={open} onOpenChange={o=>!o&&onClose()}><Dialog.Portal><Dialog.Overlay className="modal-overlay"/><Dialog.Content className={`modal ${wide?'wide':''}`}><div className="section-head"><div><Dialog.Title>{title}</Dialog.Title><Dialog.Description>{description||'Configure and save your changes.'}</Dialog.Description></div><Dialog.Close className="icon-button" aria-label="Close dialog"><X size={18}/></Dialog.Close></div>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>}
export function StatusBadge({status}:{status:string}){const label:Record<string,string>={complete:'Complete',limit_reached:'Iteration limit',interrupted:'Interrupted',running:'Running',queued:'Queued',failed:'Failed',cancelled:'Cancelled',ready:'Ready',approved:'Approved',rejected:'Changes required',connected:'Connected',untested:'Not tested',error:'Connection error'};return <span className={`status status-${status}`}>{status==='running'?<LoaderCircle size={12} className="spin"/>:['complete','approved','connected'].includes(status)?<Check size={12}/>:status==='limit_reached'?<RotateCcw size={12}/>:<span className="status-dot"/>}{label[status]||status}</span>}
export function EmptyState({title,description,action,to}:{title:string;description:string;action?:string;to?:string}){return <div className="empty"><div className="empty-icon"><Workflow size={26}/></div><h3>{title}</h3><p>{description}</p>{action&&to&&<Link className="button primary" to={to}>{action}<ArrowRight size={15}/></Link>}</div>}
export function ErrorState({error,retry}:{error:Error;retry?:()=>void}){const isolated=error instanceof ApiError&&error.code==='TenantIsolationViolationException';return <div role="alert" className="error-panel"><AlertCircle size={22}/><div><h3>{isolated?'Workspace access blocked':'Something needs your attention'}</h3><p>{error.message}</p><div className="actions">{retry&&<button onClick={retry}>Try again</button>}<Link to="/" className="button">Return to workspace</Link></div></div></div>}
export function Loading({text='Loading workspace data…'}:{text?:string}){return <div className="skeleton-panel" role="status"><LoaderCircle size={20} className="spin"/><span>{text}</span><div className="skeleton"/><div className="skeleton short"/></div>}
export function PageHeading({eyebrow,title,description,children}:{eyebrow?:string;title:string;description:string;children?:ReactNode}){return <div className="page-heading"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h1>{title}</h1><p>{description}</p></div>{children&&<div className="actions">{children}</div>}</div>}
export function Field({label,hint,children}:{label:string;hint?:string;children:ReactNode}){const id=useId();return <div className="field"><label htmlFor={id}>{label}</label>{isValidElement(children)?cloneElement(children as ReactElement<{id:string;'aria-describedby'?:string}>,{id,'aria-describedby':hint?`${id}-hint`:undefined}):children}{hint&&<small id={`${id}-hint`}>{hint}</small>}</div>}
export function Confirm({open,onClose,onConfirm,title,description,busy=false}:{open:boolean;onClose:()=>void;onConfirm:()=>void;title:string;description:string;busy?:boolean}){return <Modal open={open} onClose={onClose} title={title} description={description}><div className="actions end"><button onClick={onClose}>Keep it</button><button className="danger" disabled={busy} onClick={onConfirm}>{busy?'Working…':'Confirm'}</button></div></Modal>}
