import {useState} from 'react';
import {Check,ChevronRight,Code2,ListTree,MessagesSquare,ShieldCheck,RotateCcw,LoaderCircle,Terminal,FileCode2,AlertTriangle,ArrowUpRight} from 'lucide-react';
import {useRun} from '../app/useRun';
import {MarkdownOutput} from '../components/ArtifactView';
import {duration} from '../lib/api';
import {terminal,roleNames,type Run,type Session,type StageResult,type PlanArtifact,type ReviewReport,type BuildArtifact} from '../types';
const icons={discussion:MessagesSquare,planning:ListTree,building:Code2,review:ShieldCheck};
export type InspectorTab='Files'|'Changes'|'Plan'|'Review'|'Terminal'|'Logs';
export function Conversation({session,onInspect}:{session:Session;onInspect:(tab:InspectorTab,runId?:string,path?:string)=>void}){
 const [visible,setVisible]=useState(15);
 return <div className="conversation-thread">{session.messages.length>visible&&<button className="history-more" onClick={()=>setVisible(v=>v+15)}>Load earlier instructions</button>}{session.messages.slice(-visible).map(message=><section className="conversation-turn" key={message.id}><div className="user-message"><span className="message-author">You</span><p>{message.content}</p></div><RunTurn id={message.run_id} onInspect={onInspect}/></section>)}</div>
}
function RunTurn({id,onInspect}:{id:string;onInspect:(tab:InspectorTab,runId?:string,path?:string)=>void}){
 const q=useRun(id);const run=q.data;
 if(q.error)return <div className="thread-error">{q.error.message}</div>;
 if(!run)return <div className="thread-loading"><LoaderCircle size={14} className="spin"/>Opening execution…</div>;
 const live=!terminal(run.status);const unread=run.workflow.stages.filter(s=>!run.stages.some(r=>r.stage_id===s.id));
 const lastReview=[...run.stages].reverse().find(s=>s.role==='review'&&s.artifact)?.artifact as ReviewReport|undefined;
 const reads=run.events.find(e=>e.type==='files.read');
 return <div className="agent-turn"><div className="frontier-author"><span className="frontier-spark">✳</span><strong>Frontier</strong><span>{live?'Working with your AI team':run.status==='complete'?'Completed':run.status==='limit_reached'?'Iteration limit reached':'Stopped'}</span><small>{run.iteration>0?`Iteration ${run.iteration} of ${run.max_workflow_iterations}`:''}</small></div>{reads&&<button className="inline-activity" onClick={()=>onInspect('Files',id)}><FileCode2 size={13}/>{reads.message}<ChevronRight size={12}/></button>}<div className="agent-activity-stack">{run.stages.map(s=><StageBlock key={s.id} stage={s} run={run} inspect={tab=>onInspect(tab,id)}/>)}{live&&unread.map(s=>{const Icon=icons[s.role];return <div className="agent-waiting" key={s.id}><Icon size={14}/><strong>{roleNames[s.role]}</strong><span>{run.models[s.model_id]?.name}</span><small>Waiting</small></div>})}</div>{run.changes?.length>0&&<div className="changed-summary"><button onClick={()=>onInspect('Changes',id)}><FileCode2 size={14}/>{run.changes.filter(c=>c.status==='applied').length||run.changes.length} files {run.changes.some(c=>c.status==='applied')?'changed':'proposed'}<ChevronRight size={13}/></button><div>{run.changes.slice(-6).map(c=><button key={c.id} onClick={()=>onInspect('Changes',id,c.path)}><span className={c.kind==='added'?'file-added':'file-modified'}>{c.kind==='added'?'A':'M'}</span>{c.path}</button>)}</div></div>}{run.commands?.length>0&&<button className="inline-activity command-summary" onClick={()=>onInspect('Terminal',id)}><Terminal size={14}/>{run.commands.some(c=>c.status==='running')?'Running project checks…':`${run.commands.filter(c=>c.status==='completed').length} / ${run.commands.length} project checks passed`}<ChevronRight size={13}/></button>}{run.error&&<div className="thread-alert"><AlertTriangle size={16}/><div><strong>{run.status==='limit_reached'?'The review cycle limit was reached.':'Execution stopped.'}</strong><p>{run.error}</p><button onClick={()=>onInspect('Review',id)}>Inspect feedback<ArrowUpRight size={12}/></button></div></div>}{run.status==='complete'&&<div className="thread-completion"><Check size={15}/><span>Complete · {lastReview?'Approved by reviewer':'Project check passed'}{lastReview?` · ${Math.round(lastReview.quality_score*100)}/100`:''}</span><small>{duration(run.started_at,run.finished_at)}</small></div>}</div>
}
function StageBlock({stage,run,inspect}:{stage:StageResult;run:Run;inspect:(tab:InspectorTab)=>void}){
 const [expanded,setExpanded]=useState(false);const Icon=icons[stage.role];const plan=stage.role==='planning'?stage.artifact as PlanArtifact:null,review=stage.role==='review'?stage.artifact as ReviewReport:null,build=stage.role==='building'?stage.artifact as BuildArtifact:null;
 const running=stage.status==='running';
 return <div className={`agent-block ${running?'working':''} ${review&&!review.approved?'needs-changes':''}`}><button className="agent-block-header" onClick={()=>setExpanded(!expanded)} aria-expanded={expanded}><span className={`agent-role-icon ${stage.role}`}><Icon size={15}/></span><strong>{roleNames[stage.role]}</strong><span className="agent-model" title={run.models[stage.model_id]?.model_name}>{run.models[stage.model_id]?.name||'Model unavailable'}</span><span className="agent-block-state">{running?<><LoaderCircle size={12} className="spin"/>Working</>:review?<>{review.approved?<Check size={12}/>:<RotateCcw size={12}/>} {review.approved?'Approved':'Changes requested'}</>:stage.status==='completed'?<><Check size={12}/>{stage.role==='planning'?'Plan complete':stage.role==='building'?'Build complete':'Context established'}</>:stage.status}</span><ChevronRight size={13} className={expanded?'expanded-chevron':''}/></button>{plan&&<div className="inline-plan"><strong>{plan.title}</strong><ol>{plan.execution_steps.slice(0,expanded?undefined:3).map((step,i)=><li key={i}>{step}</li>)}</ol>{plan.execution_steps.length>3&&!expanded&&<small>+ {plan.execution_steps.length-3} more steps</small>}<button onClick={()=>inspect('Plan')}>Open full plan<ArrowUpRight size={12}/></button></div>}{review&&!review.approved&&<div className="inline-review">{review.detected_vulnerabilities.length>0&&<><strong>Security findings</strong><ul>{review.detected_vulnerabilities.map((v,i)=><li key={i}>{v}</li>)}</ul></>}{review.rejection_reasons.length>0&&<><strong>Reviewer feedback</strong><ul>{review.rejection_reasons.map((v,i)=><li key={i}>{v}</li>)}</ul></>}<p><RotateCcw size={12}/>{stage.iteration<run.iteration?'Feedback sent to the planner. The next iteration follows below.':!terminal(run.status)?'Frontier is sending this feedback back to the planner.':'Feedback is preserved. Continue after increasing the iteration limit.'}</p></div>}{build&&<div className="inline-build"><MarkdownOutput text={expanded?build.summary:build.summary.slice(0,450)+(build.summary.length>450?'…':'')}/></div>}{expanded&&!plan&&!build&&!review&&stage.output&&<div className="expanded-output"><MarkdownOutput text={stage.output}/></div>}{expanded&&review?.approved&&<div className="expanded-output"><p>Quality score: {Math.round(review.quality_score*100)} / 100. No unresolved findings reported.</p><button className="inline-link" onClick={()=>inspect('Review')}>Inspect review<ArrowUpRight size={12}/></button></div>}{running&&<div className="agent-working-caption"><span>{duration(stage.started_at,null)} · </span>{stage.role==='planning'&&stage.iteration>1?`Revising the plan with reviewer feedback · Iteration ${stage.iteration}`:stage.role==='building'?'Preparing project changes and verification commands':stage.role==='review'?'Checking the deliverable and actual verification results':'Reading the objective and project context'}</div>}</div>
}
